feat: add installation instruction to documentation
whittle-org/whittle pull request #121
Opened 2024-09-09 14:05 UTC by aaronkl

#### Reference Issues/PRs
#120 

#### What does this implement/fix? Explain your changes.

add installation instruction to documentation

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the
terms of your choice.

2024-09-09 14:37 UTC, timurcarstensen approved these changes
LGTM, shall we deploy the new docs once this is merged? If so, shall we create a new release for that?

2024-09-10 10:33 UTC, rheasukthanker requested changes
LGTM. Could we add a link to the tutorial notebook to the readme before we merge this PR?

2024-09-10 10:51 UTC, timurcarstensen approved these changes

2024-09-10 14:25 UTC, rheasukthanker approved these changes

2024-09-10 14:28 UTC, merged