fix: fixed type hints
whittle-org/whittle pull request #167
Opened 2024-11-07 18:47 UTC by zeqri

Reference Issues/PRs

removes warnings when running  ```mkdocs build --clean --strict```

2024-11-07 20:34 UTC, timurcarstensen requested changes
Thanks a lot! :) could you also make sure that you add update the flags for mkdocs in: 
- [x] `docs.yml`
- [ ] `release.yml`

2024-11-07 20:34 UTC, timurcarstensen commented on whittle/training_strategies/ats.py
imports are supposed to be ordered in this format: 
1. standard library imports (e.g., `os`, `typing`, etc. see [here](https://docs.python.org/3/library/index.html))
2. third party imports (e.g., `torch`, `numpy`, etc.)
3. local imports (your own code such as the code in whittle)

2024-11-07 20:34 UTC, timurcarstensen commented on whittle/training_strategies/random_linear.py
see previous comment

2024-11-07 20:34 UTC, timurcarstensen commented on whittle/training_strategies/sandwich.py
see previous comment

2024-11-08 09:37 UTC, zeqri commented on whittle/training_strategies/ats.py
understood

2024-11-08 15:05 UTC, merged